remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: [Rezonator Guide]
description: [Dynamics of Human Engagement]

theme: jekyll-theme-leap-day

show_downloads: true

github:
  repository_url: https://johnwdubois.github.io/rezonator/
  zip_url: https://github.com/johnwdubois/rezonator/raw/master/Executables/Windows/Rezonator%201.0.8.zip
  tar_url: https://github.com/johnwdubois/rezonator/raw/master/Executables/Mac/Rezonator%201.0.8.dmg.zip
